name: Alerta Discord

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{\"content\": \"Novo push no repositório realizado com sucesso!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}