name: Alerta para Discord

on:
  push:


jobs:
  alerta:
    runs-on: ubuntu-latest


    steps:
      - name: Enviar mensagem para Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          --data '{"content":"🚀 Push no repositório ${{ github.repository }} por ${{ github.actor }}"}' \
          ${{ secrets.DISCORD_WEBHOOK }}
          